backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: posts
    label: Post
    folder: content/blog
    path: '{{year}}-{{month}}-{{day}}-{{title}}/index'
    create: true
    slug: index
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Date', name: 'date', widget: 'datetime'}
      - { label: 'Description', name: 'description', widget: 'string'}
      - { label: 'Content', name: 'body', width: 'markdown'}

